# Generated by Django 3.2.5 on 2021-10-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inkedin',
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Account Anda di Linkedin. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='Misal: bisma@gmail.com. Field ini boleh dikosongkan.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, help_text='Account Anda di FB. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Account Anda di IG. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Misal: New Delhi, India. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Misal: Bisma. Field ini tidak boleh dikosongkan.', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', help_text='Misal foto Anda. Field ini boleh dikosongkan.', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_intro',
            field=models.CharField(blank=True, help_text='Keterangan ringkas ttg Anda. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stackoverflow',
            field=models.CharField(blank=True, help_text='Account Anda di Stackoverflow. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Account Anda di TG. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, help_text='Account Anda di Twt. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, help_text='Misal: Kakek Bisma. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube',
            field=models.CharField(blank=True, help_text='Account Anda di Ytb. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
    ]
