# Generated by Django 3.2.5 on 2021-10-23 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20211023_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Klik pilih user. Field ini boleh dikosongkan.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, help_text='Misal: https://www.bisma.com Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Klik pilih owner. Field ini boleh dikosongkan.', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(help_text='Misal: PHP. Field ini boleh dikosongkan.', max_length=50),
        ),
    ]
