# Generated by Django 3.2.5 on 2021-10-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211023_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, help_text='Account Anda di Github. Field ini boleh dikosongkan.', max_length=200, null=True),
        ),
    ]
