# Generated by Django 3.2.5 on 2021-10-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Field ini boleh dikosongkan.', null=True),
        ),
    ]
