# Generated by Django 3.2.5 on 2021-10-23 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(help_text='Misal: Clone Twitter. Field ini tidak boleh dikosongkan.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Field ini boleh dikosongkan.', null=True)),
                ('featured_image', models.ImageField(blank=True, default='projects/default.jpg', null=True, upload_to='projects/')),
                ('demo_link', models.CharField(blank=True, help_text='Misal: https:www.demo.com Field ini boleh dikosongkan.', max_length=2000, null=True)),
                ('source_link', models.CharField(blank=True, help_text='Misal: https:www.demo.com Field ini boleh dikosongkan.', max_length=2000, null=True)),
                ('vote_total', models.IntegerField(blank=True, default=0, help_text='Field ini boleh dikosongkan.', null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, help_text='Field ini boleh dikosongkan.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Field untuk tanggal dibuat.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Field untuk tanggal diupdate.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Klik pilih owner. Field ini boleh dikosongkan.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='decors.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(blank=True, help_text='Misal: The City. Field ini boleh dikosongkan.', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Field untuk tanggal dibuat.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Field untuk tanggal diupdate.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, help_text='Field ini boleh dikosongkan.', null=True)),
                ('value', models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], help_text='Klik pilih vote type. Field ini boleh dikosongkan.', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Field untuk tanggal dibuat.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Field untuk tanggal diupdate.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project', models.ForeignKey(blank=True, help_text='Klik pilih proyek. Field ini boleh dikosongkan.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Boleh pilih 1 atau lebih tags. Field ini boleh dikosongkan.', to='projects.Tag'),
        ),
    ]
